ALTER TABLE camp_certificate_template
    ADD COLUMN IF NOT EXISTS course_x REAL NOT NULL DEFAULT 0.5,
    ADD COLUMN IF NOT EXISTS course_y REAL NOT NULL DEFAULT 0.62,
    ADD COLUMN IF NOT EXISTS course_size INTEGER NOT NULL DEFAULT 16,
    ADD COLUMN IF NOT EXISTS course_color VARCHAR(7) NOT NULL DEFAULT '#141414',
    ADD COLUMN IF NOT EXISTS course_align VARCHAR(8) NOT NULL DEFAULT 'center';