ALTER TABLE invites
    ADD COLUMN IF NOT EXISTS target_role VARCHAR(32) NOT NULL DEFAULT 'employee',
    ADD COLUMN IF NOT EXISTS link_table VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS link_id INTEGER,
    ADD COLUMN IF NOT EXISTS redirect_uri TEXT NOT NULL DEFAULT '/cabinet';